#image: docker:latest

#services:
#  - docker:dind

stages:
  - build
variables:
  GADGET_CONTAINER: nextthingco/buildroot-development-container:master

before_script:
  - echo "Building gadget os..."
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  - docker pull $GADGET_CONTAINER

build:
  stage: build
  script:
    - env

  artifacts:
    paths:
      - output/images/rootfs.ubi.sparse
      - output/images/spl-40000-1000-100.bin
      - output/images/uboot-40000.bin
      - output/images/uboot.script