image: docker:latest

services:
  - docker:dind

stages:
  - build
  - howitzer
  - upload

variables:
  GADGET_CONTAINER: $CI_REGISTRY/nextthingco/buildroot-development-container:master
  HOWITZER_CONTAINER: $CI_REGISTRY/gadget/howitzer-container:master
  UPLOAD_CONTAINER: $CI_REGISTRY/nextthingco/ci-tools:stable
  ARTIFACT_0: output/images/rootfs.ubi.sparse
  ARTIFACT_1: output/images/spl-40000-1000-100.bin
  ARTIFACT_2: output/images/uboot-40000.bin
  ARTIFACT_3: output/images/uboot.script
  ARTIFACT_4: output/images/${CI_BUILD_REF_SLUG}-chip-pro-${CI_PROJECT_NAME}-b${CI_BUILD_ID}-Toshiba_512_MLC.chp
  SLACK_CHANNEL: $BUILD_SLACK_CHANNEL
  SLACK_HOOK: $BUILD_SLACK_HOOK

before_script:
  - echo "Building gadget os..."
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  - docker pull $GADGET_CONTAINER

build:
  stage: build
  script:
    - scripts/build-container
    - scripts/build-gadget make -s chippro_docker_defconfig
    - scripts/build-gadget make -s all
    - ls -la
    - ls output/images
#  cache:
#    key: ${CI_BUILD_REF_NAME}${CI_BUILD_ID}
#    paths:
#      - output/

#howitzer:
#  stage: howitzer
#  script:
#    - ls -la
    - ls output/images
    - docker pull $HOWITZER_CONTAINER
    - docker run -v $PWD:/opt/images -w /opt/images --rm $HOWITZER_CONTAINER ls -la
    - docker run -v $PWD:/opt/images -w /opt/images --rm $HOWITZER_CONTAINER ls -la output/images
    - docker run -v $PWD:/opt/images -w /opt/images --rm $HOWITZER_CONTAINER /bin/bash -x scripts/flash-gadget
    - docker run -v $PWD:/opt/images -w /opt/images --rm $HOWITZER_CONTAINER howitzer nand Toshiba_512M_MLC chp /opt/images/fel.chp chp /opt/images/fastboot.chp -f /opt/images/${ARTIFACT_4}
#    - rm output/images/fel.chp output/images/fastboot.chp
#  cache:
#    key: ${CI_BUILD_REF_NAME}${CI_BUILD_ID}
#    paths:
#      - output/

#upload:
#  stage: upload
#  script:
    - docker pull $UPLOAD_CONTAINER
    - docker run
      -e GHVAR_SLACK_WEBHOOK=${GHVAR_SLACK_WEBHOOK}
      -e GHVAR_AWS_ID=${GHVAR_AWS_ID}
      -e GHVAR_AWS_PW=${GHVAR_AWS_PW}
      -e GHVAR_AWS_REGION=${GHVAR_AWS_REGION}
      -e CI_PROJECT_NAME=${CI_PROJECT_NAME}
      -e CI_BUILD_REF_NAME=${CI_BUILD_REF_SLUG}
      -e CI_BUILD_ID=${CI_BUILD_ID}
      -e ARTIFACT_0=${ARTIFACT_0}
      -e ARTIFACT_1=${ARTIFACT_1}
      -e ARTIFACT_2=${ARTIFACT_2}
      -e ARTIFACT_3=${ARTIFACT_3}
      -e ARTIFACT_4=${ARTIFACT_4}
      --rm -v $PWD:/upload -w /upload
      $UPLOAD_CONTAINER ci-s3-upload
      ${ARTIFACT_0}
      ${ARTIFACT_1}
      ${ARTIFACT_2}
      ${ARTIFACT_3}
      ${ARTIFACT_4}

