image: docker:latest

services:
  - docker:dind

stages:
  - build
  - upload
variables:
  GADGET_CONTAINER: $CI_REGISTRY/nextthingco/buildroot-development-container:master
  UPLOAD_CONTAINER: $CI_REGISTRY/nextthingco/ci-tools:stable
  ARTIFACT_0: output/images/rootfs.ubi.sparse
  ARTIFACT_1: output/images/spl-40000-1000-100.bin
  ARTIFACT_2: output/images/uboot-40000.bin
  ARTIFACT_3: output/images/uboot.script

before_script:
  - echo "Building gadget os..."
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  - docker pull $GADGET_CONTAINER

build:
  stage: build
  script:
    - scripts/build-container
    - scripts/build-gadget make -s chippro_docker_defconfig
    - scripts/build-gadget make -s all

  artifacts:
    paths:
      - output/images/rootfs.ubi.sparse
      - output/images/spl-40000-1000-100.bin
      - output/images/uboot-40000.bin
      - output/images/uboot.script

upload:
  stage: upload
  script:
    - docker pull $UPLOAD_CONTAINER
    - docker run \
      -e GHVAR_AWS_ID=${GHVAR_AWS_ID} \
      -e GHVAR_AWS_PW=${GHVAR_AWS_PW} \
      -e GHVAR_AWS_REGION=${GHVAR_AWS_REGION} \
      -e CI_PROJECT_NAME=${CI_PROJECT_NAME} \
      -e CI_BUILD_REF_NAME=${CI_BUILD_REF_NAME} \
      -e CI_BUILD_ID=${CI_BUILD_ID} \
      -e ARTIFACT_0=${ARTIFACT_0} \
      -e ARTIFACT_1=${ARTIFACT_1} \
      -e ARTIFACT_2=${ARTIFACT_2} \
      -e ARTIFACT_3=${ARTIFACT_3} \
      --rm -v $PWD:/upload -w /upload \
      $CONTAINER_IMAGE_TEST ci-s3-upload \
      ${ARTIFACT_0} \
      ${ARTIFACT_1} \
      ${ARTIFACT_2} \
      ${ARTIFACT_3}

